//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Tools.Alarm;
	
	
	public partial class AlarmServer : Neo.ApplicationFramework.Tools.Alarm.AlarmServer, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmGroup m_Filter1;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_111;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_112;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_113;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_DS_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_VS_A_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_VS_A_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_VS_B_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_VS_B_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_VS_C_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_VS_C_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_FS_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_FS_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_TS_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_CS_A_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_CS_B_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_CS_C_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_MVS_1_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_MVS_1_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_MVS_2_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter1_F1_MVS_2_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmGroup m_Filter2;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_111;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_112;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_113;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_DS_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_VS_A_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_VS_A_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_VS_B_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_VS_B_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_VS_C_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_VS_C_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_FS_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_FS_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_TS_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_CS_A_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_CS_B_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_CS_C_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_MVS_1_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_MVS_1_L;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_MVS_2_H;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Filter2_F2_MVS_2_L;
		
		public AlarmServer()
		{
			this.InitializeComponent();
			this.Filter1.AlarmActive += new System.EventHandler(this.Filter1_Action_AlarmActive);
			this.Filter2.AlarmActive += new System.EventHandler(this.Filter2_Action_AlarmActive);
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmGroup Filter1
		{
			get
			{
				return this.m_Filter1;
			}
			set
			{
				this.m_Filter1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_111
		{
			get
			{
				return this.m_Filter1_F1_111;
			}
			set
			{
				this.m_Filter1_F1_111 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_112
		{
			get
			{
				return this.m_Filter1_F1_112;
			}
			set
			{
				this.m_Filter1_F1_112 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_113
		{
			get
			{
				return this.m_Filter1_F1_113;
			}
			set
			{
				this.m_Filter1_F1_113 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_DS_H
		{
			get
			{
				return this.m_Filter1_F1_DS_H;
			}
			set
			{
				this.m_Filter1_F1_DS_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_VS_A_H
		{
			get
			{
				return this.m_Filter1_F1_VS_A_H;
			}
			set
			{
				this.m_Filter1_F1_VS_A_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_VS_A_L
		{
			get
			{
				return this.m_Filter1_F1_VS_A_L;
			}
			set
			{
				this.m_Filter1_F1_VS_A_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_VS_B_H
		{
			get
			{
				return this.m_Filter1_F1_VS_B_H;
			}
			set
			{
				this.m_Filter1_F1_VS_B_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_VS_B_L
		{
			get
			{
				return this.m_Filter1_F1_VS_B_L;
			}
			set
			{
				this.m_Filter1_F1_VS_B_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_VS_C_H
		{
			get
			{
				return this.m_Filter1_F1_VS_C_H;
			}
			set
			{
				this.m_Filter1_F1_VS_C_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_VS_C_L
		{
			get
			{
				return this.m_Filter1_F1_VS_C_L;
			}
			set
			{
				this.m_Filter1_F1_VS_C_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_FS_H
		{
			get
			{
				return this.m_Filter1_F1_FS_H;
			}
			set
			{
				this.m_Filter1_F1_FS_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_FS_L
		{
			get
			{
				return this.m_Filter1_F1_FS_L;
			}
			set
			{
				this.m_Filter1_F1_FS_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_TS_H
		{
			get
			{
				return this.m_Filter1_F1_TS_H;
			}
			set
			{
				this.m_Filter1_F1_TS_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_CS_A_H
		{
			get
			{
				return this.m_Filter1_F1_CS_A_H;
			}
			set
			{
				this.m_Filter1_F1_CS_A_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_CS_B_H
		{
			get
			{
				return this.m_Filter1_F1_CS_B_H;
			}
			set
			{
				this.m_Filter1_F1_CS_B_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_CS_C_H
		{
			get
			{
				return this.m_Filter1_F1_CS_C_H;
			}
			set
			{
				this.m_Filter1_F1_CS_C_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_MVS_1_H
		{
			get
			{
				return this.m_Filter1_F1_MVS_1_H;
			}
			set
			{
				this.m_Filter1_F1_MVS_1_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_MVS_1_L
		{
			get
			{
				return this.m_Filter1_F1_MVS_1_L;
			}
			set
			{
				this.m_Filter1_F1_MVS_1_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_MVS_2_H
		{
			get
			{
				return this.m_Filter1_F1_MVS_2_H;
			}
			set
			{
				this.m_Filter1_F1_MVS_2_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter1_F1_MVS_2_L
		{
			get
			{
				return this.m_Filter1_F1_MVS_2_L;
			}
			set
			{
				this.m_Filter1_F1_MVS_2_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmGroup Filter2
		{
			get
			{
				return this.m_Filter2;
			}
			set
			{
				this.m_Filter2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_111
		{
			get
			{
				return this.m_Filter2_F2_111;
			}
			set
			{
				this.m_Filter2_F2_111 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_112
		{
			get
			{
				return this.m_Filter2_F2_112;
			}
			set
			{
				this.m_Filter2_F2_112 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_113
		{
			get
			{
				return this.m_Filter2_F2_113;
			}
			set
			{
				this.m_Filter2_F2_113 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_DS_H
		{
			get
			{
				return this.m_Filter2_F2_DS_H;
			}
			set
			{
				this.m_Filter2_F2_DS_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_VS_A_H
		{
			get
			{
				return this.m_Filter2_F2_VS_A_H;
			}
			set
			{
				this.m_Filter2_F2_VS_A_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_VS_A_L
		{
			get
			{
				return this.m_Filter2_F2_VS_A_L;
			}
			set
			{
				this.m_Filter2_F2_VS_A_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_VS_B_H
		{
			get
			{
				return this.m_Filter2_F2_VS_B_H;
			}
			set
			{
				this.m_Filter2_F2_VS_B_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_VS_B_L
		{
			get
			{
				return this.m_Filter2_F2_VS_B_L;
			}
			set
			{
				this.m_Filter2_F2_VS_B_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_VS_C_H
		{
			get
			{
				return this.m_Filter2_F2_VS_C_H;
			}
			set
			{
				this.m_Filter2_F2_VS_C_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_VS_C_L
		{
			get
			{
				return this.m_Filter2_F2_VS_C_L;
			}
			set
			{
				this.m_Filter2_F2_VS_C_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_FS_H
		{
			get
			{
				return this.m_Filter2_F2_FS_H;
			}
			set
			{
				this.m_Filter2_F2_FS_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_FS_L
		{
			get
			{
				return this.m_Filter2_F2_FS_L;
			}
			set
			{
				this.m_Filter2_F2_FS_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_TS_H
		{
			get
			{
				return this.m_Filter2_F2_TS_H;
			}
			set
			{
				this.m_Filter2_F2_TS_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_CS_A_H
		{
			get
			{
				return this.m_Filter2_F2_CS_A_H;
			}
			set
			{
				this.m_Filter2_F2_CS_A_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_CS_B_H
		{
			get
			{
				return this.m_Filter2_F2_CS_B_H;
			}
			set
			{
				this.m_Filter2_F2_CS_B_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_CS_C_H
		{
			get
			{
				return this.m_Filter2_F2_CS_C_H;
			}
			set
			{
				this.m_Filter2_F2_CS_C_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_MVS_1_H
		{
			get
			{
				return this.m_Filter2_F2_MVS_1_H;
			}
			set
			{
				this.m_Filter2_F2_MVS_1_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_MVS_1_L
		{
			get
			{
				return this.m_Filter2_F2_MVS_1_L;
			}
			set
			{
				this.m_Filter2_F2_MVS_1_L = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_MVS_2_H
		{
			get
			{
				return this.m_Filter2_F2_MVS_2_H;
			}
			set
			{
				this.m_Filter2_F2_MVS_2_H = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Filter2_F2_MVS_2_L
		{
			get
			{
				return this.m_Filter2_F2_MVS_2_L;
			}
			set
			{
				this.m_Filter2_F2_MVS_2_L = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
			this.Filter1_F1_111.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.err1_11"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_113.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.err1_13_f2"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_DS_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_DS_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_VS_A_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_VS_A_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_VS_A_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_VS_A_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_VS_B_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_VS_B_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_VS_B_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_VS_B_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_VS_C_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_VS_C_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_112.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.err1_12_f2"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_VS_C_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_VS_C_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_FS_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_FS_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_TS_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_TS_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_CS_A_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_CS_A_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_CS_B_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_CS_B_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_CS_C_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_CS_C_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_MVS_1_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_MVS_1_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_MVS_1_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_MVS_1_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_FS_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_FS_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_111.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.err1_11_f2"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_MVS_2_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_MVS_2_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_MVS_2_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_MVS_2_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_112.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.err1_12"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_113.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.err1_13"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_DS_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_DS_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_VS_A_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_VS_A_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_VS_A_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_VS_A_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_VS_B_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_VS_B_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_VS_B_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_VS_B_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_VS_C_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_VS_C_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_VS_C_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_VS_C_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_FS_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_FS_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_FS_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_FS_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_TS_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_TS_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_CS_A_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_CS_A_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_CS_B_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_CS_B_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_CS_C_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_CS_C_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_MVS_1_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_MVS_1_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter1_F1_MVS_1_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F1_MVS_1_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_MVS_2_H.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_MVS_2_H"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.Filter2_F2_MVS_2_L.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.F2_MVS_2_L"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
		}
		
		private void InitializeObjectCreations()
		{
			this.Filter1 = new Neo.ApplicationFramework.Tools.Alarm.AlarmGroup();
			this.Filter1_F1_111 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_112 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_113 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_DS_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_VS_A_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_VS_A_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_VS_B_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_VS_B_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_VS_C_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_VS_C_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_FS_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_FS_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_TS_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_CS_A_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_CS_B_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_CS_C_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_MVS_1_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_MVS_1_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_MVS_2_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter1_F1_MVS_2_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2 = new Neo.ApplicationFramework.Tools.Alarm.AlarmGroup();
			this.Filter2_F2_111 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_112 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_113 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_DS_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_VS_A_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_VS_A_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_VS_B_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_VS_B_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_VS_C_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_VS_C_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_FS_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_FS_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_TS_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_CS_A_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_CS_B_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_CS_C_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_MVS_1_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_MVS_1_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_MVS_2_H = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Filter2_F2_MVS_2_L = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_111)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_112)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_113)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_DS_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_A_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_A_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_B_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_B_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_C_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_C_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_FS_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_FS_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_TS_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_CS_A_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_CS_B_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_CS_C_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_1_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_1_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_2_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_2_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_111)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_112)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_113)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_DS_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_A_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_A_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_B_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_B_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_C_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_C_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_FS_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_FS_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_TS_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_CS_A_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_CS_B_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_CS_C_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_1_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_1_L)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_2_H)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_2_L)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_111)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_112)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_113)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_DS_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_A_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_A_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_B_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_B_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_C_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_VS_C_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_FS_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_FS_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_TS_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_CS_A_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_CS_B_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_CS_C_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_1_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_1_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_2_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter1_F1_MVS_2_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_111)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_112)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_113)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_DS_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_A_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_A_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_B_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_B_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_C_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_VS_C_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_FS_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_FS_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_TS_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_CS_A_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_CS_B_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_CS_C_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_1_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_1_L)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_2_H)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Filter2_F2_MVS_2_L)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.Filter1.AcknowledgeBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(14)))));
			this.Filter1.AcknowledgeForeColor = System.Drawing.Color.Black;
			this.Filter1.ActiveBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(19)))), ((int)(((byte)(41)))));
			this.Filter1.ActiveForeColor = System.Drawing.Color.Black;
			this.Filter1_F1_111.AcknowledgeRequired = true;
			this.Filter1_F1_111.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_111.Contacts = null;
			this.Filter1_F1_111.DefaultText = "模块1A相igbt故障";
			this.Filter1_F1_111.DisplayName = "F1_111";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString1 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString1.Text = "模块1A相igbt故障";
			this.Filter1_F1_111.DynamicString = DynamicString1;
			this.Filter1_F1_111.EnableDistribution = false;
			this.Filter1_F1_111.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_111.GroupName = "Filter1";
			this.Filter1_F1_111.History = true;
			this.Filter1_F1_111.IsDigitalValue = false;
			this.Filter1_F1_111.Name = "Filter1_F1_111";
			this.Filter1_F1_111.OutputDevices = null;
			this.Filter1_F1_111.RepeatCount = false;
			this.Filter1_F1_111.TriggerValue = 1;
			this.Filter1_F1_112.AcknowledgeRequired = true;
			this.Filter1_F1_112.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_112.Contacts = null;
			this.Filter1_F1_112.DefaultText = "模块1B相igbt故障";
			this.Filter1_F1_112.DisplayName = "F1_112";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString2 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString2.Text = "模块1B相igbt故障";
			this.Filter1_F1_112.DynamicString = DynamicString2;
			this.Filter1_F1_112.EnableDistribution = false;
			this.Filter1_F1_112.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_112.GroupName = "Filter1";
			this.Filter1_F1_112.History = true;
			this.Filter1_F1_112.IsDigitalValue = false;
			this.Filter1_F1_112.Name = "Filter1_F1_112";
			this.Filter1_F1_112.OutputDevices = null;
			this.Filter1_F1_112.RepeatCount = false;
			this.Filter1_F1_112.TriggerValue = 1;
			this.Filter1_F1_113.AcknowledgeRequired = true;
			this.Filter1_F1_113.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_113.Contacts = null;
			this.Filter1_F1_113.DefaultText = "模块1C相igbt故障";
			this.Filter1_F1_113.DisplayName = "F1_113";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString3 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString3.Text = "模块1C相igbt故障";
			this.Filter1_F1_113.DynamicString = DynamicString3;
			this.Filter1_F1_113.EnableDistribution = false;
			this.Filter1_F1_113.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_113.GroupName = "Filter1";
			this.Filter1_F1_113.History = true;
			this.Filter1_F1_113.IsDigitalValue = false;
			this.Filter1_F1_113.Name = "Filter1_F1_113";
			this.Filter1_F1_113.OutputDevices = null;
			this.Filter1_F1_113.RepeatCount = false;
			this.Filter1_F1_113.TriggerValue = 1;
			this.Filter1_F1_DS_H.AcknowledgeRequired = true;
			this.Filter1_F1_DS_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_DS_H.Contacts = null;
			this.Filter1_F1_DS_H.DefaultText = "模块1三相不平衡";
			this.Filter1_F1_DS_H.DisplayName = "F1_DS_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString4 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString4.Text = "模块1三相不平衡";
			this.Filter1_F1_DS_H.DynamicString = DynamicString4;
			this.Filter1_F1_DS_H.EnableDistribution = false;
			this.Filter1_F1_DS_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_DS_H.GroupName = "Filter1";
			this.Filter1_F1_DS_H.History = true;
			this.Filter1_F1_DS_H.IsDigitalValue = false;
			this.Filter1_F1_DS_H.Name = "Filter1_F1_DS_H";
			this.Filter1_F1_DS_H.OutputDevices = null;
			this.Filter1_F1_DS_H.RepeatCount = false;
			this.Filter1_F1_DS_H.TriggerValue = 1;
			this.Filter1_F1_VS_A_H.AcknowledgeRequired = true;
			this.Filter1_F1_VS_A_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_VS_A_H.Contacts = null;
			this.Filter1_F1_VS_A_H.DefaultText = "模块1电压高";
			this.Filter1_F1_VS_A_H.DisplayName = "F1_VS_A_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString5 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString5.Text = "模块1电压高";
			this.Filter1_F1_VS_A_H.DynamicString = DynamicString5;
			this.Filter1_F1_VS_A_H.EnableDistribution = false;
			this.Filter1_F1_VS_A_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_VS_A_H.GroupName = "Filter1";
			this.Filter1_F1_VS_A_H.History = true;
			this.Filter1_F1_VS_A_H.IsDigitalValue = false;
			this.Filter1_F1_VS_A_H.Name = "Filter1_F1_VS_A_H";
			this.Filter1_F1_VS_A_H.OutputDevices = null;
			this.Filter1_F1_VS_A_H.RepeatCount = false;
			this.Filter1_F1_VS_A_H.TriggerValue = 1;
			this.Filter1_F1_VS_A_L.AcknowledgeRequired = true;
			this.Filter1_F1_VS_A_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_VS_A_L.Contacts = null;
			this.Filter1_F1_VS_A_L.DefaultText = "模块1电压低";
			this.Filter1_F1_VS_A_L.DisplayName = "F1_VS_A_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString6 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString6.Text = "模块1电压低";
			this.Filter1_F1_VS_A_L.DynamicString = DynamicString6;
			this.Filter1_F1_VS_A_L.EnableDistribution = false;
			this.Filter1_F1_VS_A_L.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_VS_A_L.GroupName = "Filter1";
			this.Filter1_F1_VS_A_L.History = true;
			this.Filter1_F1_VS_A_L.IsDigitalValue = false;
			this.Filter1_F1_VS_A_L.Name = "Filter1_F1_VS_A_L";
			this.Filter1_F1_VS_A_L.OutputDevices = null;
			this.Filter1_F1_VS_A_L.RepeatCount = false;
			this.Filter1_F1_VS_A_L.TriggerValue = 1;
			this.Filter1_F1_VS_B_H.AcknowledgeRequired = true;
			this.Filter1_F1_VS_B_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_VS_B_H.Contacts = null;
			this.Filter1_F1_VS_B_H.DefaultText = "模块1B相电压高";
			this.Filter1_F1_VS_B_H.DisplayName = "F1_VS_B_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString7 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString7.Text = "模块1B相电压高";
			this.Filter1_F1_VS_B_H.DynamicString = DynamicString7;
			this.Filter1_F1_VS_B_H.EnableDistribution = false;
			this.Filter1_F1_VS_B_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_VS_B_H.GroupName = "Filter1";
			this.Filter1_F1_VS_B_H.History = true;
			this.Filter1_F1_VS_B_H.IsDigitalValue = false;
			this.Filter1_F1_VS_B_H.Name = "Filter1_F1_VS_B_H";
			this.Filter1_F1_VS_B_H.OutputDevices = null;
			this.Filter1_F1_VS_B_H.RepeatCount = false;
			this.Filter1_F1_VS_B_H.TriggerValue = 1;
			this.Filter1_F1_VS_B_L.AcknowledgeRequired = true;
			this.Filter1_F1_VS_B_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_VS_B_L.Contacts = null;
			this.Filter1_F1_VS_B_L.DefaultText = "模块1B相电压低";
			this.Filter1_F1_VS_B_L.DisplayName = "F1_VS_B_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString8 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString8.Text = "模块1B相电压低";
			this.Filter1_F1_VS_B_L.DynamicString = DynamicString8;
			this.Filter1_F1_VS_B_L.EnableDistribution = false;
			this.Filter1_F1_VS_B_L.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_VS_B_L.GroupName = "Filter1";
			this.Filter1_F1_VS_B_L.History = true;
			this.Filter1_F1_VS_B_L.IsDigitalValue = false;
			this.Filter1_F1_VS_B_L.Name = "Filter1_F1_VS_B_L";
			this.Filter1_F1_VS_B_L.OutputDevices = null;
			this.Filter1_F1_VS_B_L.RepeatCount = false;
			this.Filter1_F1_VS_B_L.TriggerValue = 1;
			this.Filter1_F1_VS_C_H.AcknowledgeRequired = true;
			this.Filter1_F1_VS_C_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_VS_C_H.Contacts = null;
			this.Filter1_F1_VS_C_H.DefaultText = "模块1C相电压高";
			this.Filter1_F1_VS_C_H.DisplayName = "F1_VS_C_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString9 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString9.Text = "模块1C相电压高";
			this.Filter1_F1_VS_C_H.DynamicString = DynamicString9;
			this.Filter1_F1_VS_C_H.EnableDistribution = false;
			this.Filter1_F1_VS_C_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_VS_C_H.GroupName = "Filter1";
			this.Filter1_F1_VS_C_H.History = true;
			this.Filter1_F1_VS_C_H.IsDigitalValue = false;
			this.Filter1_F1_VS_C_H.Name = "Filter1_F1_VS_C_H";
			this.Filter1_F1_VS_C_H.OutputDevices = null;
			this.Filter1_F1_VS_C_H.RepeatCount = false;
			this.Filter1_F1_VS_C_H.TriggerValue = 1;
			this.Filter1_F1_VS_C_L.AcknowledgeRequired = true;
			this.Filter1_F1_VS_C_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_VS_C_L.Contacts = null;
			this.Filter1_F1_VS_C_L.DefaultText = "模块1C相电压低";
			this.Filter1_F1_VS_C_L.DisplayName = "F1_VS_C_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString10 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString10.Text = "模块1C相电压低";
			this.Filter1_F1_VS_C_L.DynamicString = DynamicString10;
			this.Filter1_F1_VS_C_L.EnableDistribution = false;
			this.Filter1_F1_VS_C_L.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_VS_C_L.GroupName = "Filter1";
			this.Filter1_F1_VS_C_L.History = true;
			this.Filter1_F1_VS_C_L.IsDigitalValue = false;
			this.Filter1_F1_VS_C_L.Name = "Filter1_F1_VS_C_L";
			this.Filter1_F1_VS_C_L.OutputDevices = null;
			this.Filter1_F1_VS_C_L.RepeatCount = false;
			this.Filter1_F1_VS_C_L.TriggerValue = 1;
			this.Filter1_F1_FS_H.AcknowledgeRequired = true;
			this.Filter1_F1_FS_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_FS_H.Contacts = null;
			this.Filter1_F1_FS_H.DefaultText = "模块1频率高";
			this.Filter1_F1_FS_H.DisplayName = "F1_FS_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString11 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString11.Text = "模块1频率高";
			this.Filter1_F1_FS_H.DynamicString = DynamicString11;
			this.Filter1_F1_FS_H.EnableDistribution = false;
			this.Filter1_F1_FS_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_FS_H.GroupName = "Filter1";
			this.Filter1_F1_FS_H.History = true;
			this.Filter1_F1_FS_H.IsDigitalValue = false;
			this.Filter1_F1_FS_H.Name = "Filter1_F1_FS_H";
			this.Filter1_F1_FS_H.OutputDevices = null;
			this.Filter1_F1_FS_H.RepeatCount = false;
			this.Filter1_F1_FS_H.TriggerValue = 1;
			this.Filter1_F1_FS_L.AcknowledgeRequired = true;
			this.Filter1_F1_FS_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_FS_L.Contacts = null;
			this.Filter1_F1_FS_L.DefaultText = "模块1频率低";
			this.Filter1_F1_FS_L.DisplayName = "F1_FS_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString12 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString12.Text = "模块1频率低";
			this.Filter1_F1_FS_L.DynamicString = DynamicString12;
			this.Filter1_F1_FS_L.EnableDistribution = false;
			this.Filter1_F1_FS_L.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_FS_L.GroupName = "Filter1";
			this.Filter1_F1_FS_L.History = true;
			this.Filter1_F1_FS_L.IsDigitalValue = false;
			this.Filter1_F1_FS_L.Name = "Filter1_F1_FS_L";
			this.Filter1_F1_FS_L.OutputDevices = null;
			this.Filter1_F1_FS_L.RepeatCount = false;
			this.Filter1_F1_FS_L.TriggerValue = 1;
			this.Filter1_F1_TS_H.AcknowledgeRequired = true;
			this.Filter1_F1_TS_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_TS_H.Contacts = null;
			this.Filter1_F1_TS_H.DefaultText = "模块1温度高";
			this.Filter1_F1_TS_H.DisplayName = "F1_TS_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString13 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString13.Text = "模块1温度高";
			this.Filter1_F1_TS_H.DynamicString = DynamicString13;
			this.Filter1_F1_TS_H.EnableDistribution = false;
			this.Filter1_F1_TS_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_TS_H.GroupName = "Filter1";
			this.Filter1_F1_TS_H.History = true;
			this.Filter1_F1_TS_H.IsDigitalValue = false;
			this.Filter1_F1_TS_H.Name = "Filter1_F1_TS_H";
			this.Filter1_F1_TS_H.OutputDevices = null;
			this.Filter1_F1_TS_H.RepeatCount = false;
			this.Filter1_F1_TS_H.TriggerValue = 1;
			this.Filter1_F1_CS_A_H.AcknowledgeRequired = true;
			this.Filter1_F1_CS_A_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_CS_A_H.Contacts = null;
			this.Filter1_F1_CS_A_H.DefaultText = "模块1A相输出电流高";
			this.Filter1_F1_CS_A_H.DisplayName = "F1_CS_A_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString14 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString14.Text = "模块1A相输出电流高";
			this.Filter1_F1_CS_A_H.DynamicString = DynamicString14;
			this.Filter1_F1_CS_A_H.EnableDistribution = false;
			this.Filter1_F1_CS_A_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_CS_A_H.GroupName = "Filter1";
			this.Filter1_F1_CS_A_H.History = true;
			this.Filter1_F1_CS_A_H.IsDigitalValue = false;
			this.Filter1_F1_CS_A_H.Name = "Filter1_F1_CS_A_H";
			this.Filter1_F1_CS_A_H.OutputDevices = null;
			this.Filter1_F1_CS_A_H.RepeatCount = false;
			this.Filter1_F1_CS_A_H.TriggerValue = 1;
			this.Filter1_F1_CS_B_H.AcknowledgeRequired = true;
			this.Filter1_F1_CS_B_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_CS_B_H.Contacts = null;
			this.Filter1_F1_CS_B_H.DefaultText = "模块1B相输出电流高";
			this.Filter1_F1_CS_B_H.DisplayName = "F1_CS_B_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString15 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString15.Text = "模块1B相输出电流高";
			this.Filter1_F1_CS_B_H.DynamicString = DynamicString15;
			this.Filter1_F1_CS_B_H.EnableDistribution = false;
			this.Filter1_F1_CS_B_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_CS_B_H.GroupName = "Filter1";
			this.Filter1_F1_CS_B_H.History = true;
			this.Filter1_F1_CS_B_H.IsDigitalValue = false;
			this.Filter1_F1_CS_B_H.Name = "Filter1_F1_CS_B_H";
			this.Filter1_F1_CS_B_H.OutputDevices = null;
			this.Filter1_F1_CS_B_H.RepeatCount = false;
			this.Filter1_F1_CS_B_H.TriggerValue = 1;
			this.Filter1_F1_CS_C_H.AcknowledgeRequired = true;
			this.Filter1_F1_CS_C_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_CS_C_H.Contacts = null;
			this.Filter1_F1_CS_C_H.DefaultText = "模块1C相输出电流高";
			this.Filter1_F1_CS_C_H.DisplayName = "F1_CS_C_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString16 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString16.Text = "模块1C相输出电流高";
			this.Filter1_F1_CS_C_H.DynamicString = DynamicString16;
			this.Filter1_F1_CS_C_H.EnableDistribution = false;
			this.Filter1_F1_CS_C_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_CS_C_H.GroupName = "Filter1";
			this.Filter1_F1_CS_C_H.History = true;
			this.Filter1_F1_CS_C_H.IsDigitalValue = false;
			this.Filter1_F1_CS_C_H.Name = "Filter1_F1_CS_C_H";
			this.Filter1_F1_CS_C_H.OutputDevices = null;
			this.Filter1_F1_CS_C_H.RepeatCount = false;
			this.Filter1_F1_CS_C_H.TriggerValue = 1;
			this.Filter1_F1_MVS_1_H.AcknowledgeRequired = true;
			this.Filter1_F1_MVS_1_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_MVS_1_H.Contacts = null;
			this.Filter1_F1_MVS_1_H.DefaultText = "模块1直流母线1电压高";
			this.Filter1_F1_MVS_1_H.DisplayName = "F1_MVS_1_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString17 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString17.Text = "模块1直流母线1电压高";
			this.Filter1_F1_MVS_1_H.DynamicString = DynamicString17;
			this.Filter1_F1_MVS_1_H.EnableDistribution = false;
			this.Filter1_F1_MVS_1_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_MVS_1_H.GroupName = "Filter1";
			this.Filter1_F1_MVS_1_H.History = true;
			this.Filter1_F1_MVS_1_H.IsDigitalValue = false;
			this.Filter1_F1_MVS_1_H.Name = "Filter1_F1_MVS_1_H";
			this.Filter1_F1_MVS_1_H.OutputDevices = null;
			this.Filter1_F1_MVS_1_H.RepeatCount = false;
			this.Filter1_F1_MVS_1_H.TriggerValue = 1;
			this.Filter1_F1_MVS_1_L.AcknowledgeRequired = true;
			this.Filter1_F1_MVS_1_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_MVS_1_L.Contacts = null;
			this.Filter1_F1_MVS_1_L.DefaultText = "模块1直流母线1电压低";
			this.Filter1_F1_MVS_1_L.DisplayName = "F1_MVS_1_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString18 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString18.Text = "模块1直流母线1电压低";
			this.Filter1_F1_MVS_1_L.DynamicString = DynamicString18;
			this.Filter1_F1_MVS_1_L.EnableDistribution = false;
			this.Filter1_F1_MVS_1_L.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_MVS_1_L.GroupName = "Filter1";
			this.Filter1_F1_MVS_1_L.History = true;
			this.Filter1_F1_MVS_1_L.IsDigitalValue = false;
			this.Filter1_F1_MVS_1_L.Name = "Filter1_F1_MVS_1_L";
			this.Filter1_F1_MVS_1_L.OutputDevices = null;
			this.Filter1_F1_MVS_1_L.RepeatCount = false;
			this.Filter1_F1_MVS_1_L.TriggerValue = 1;
			this.Filter1_F1_MVS_2_H.AcknowledgeRequired = true;
			this.Filter1_F1_MVS_2_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_MVS_2_H.Contacts = null;
			this.Filter1_F1_MVS_2_H.DefaultText = "模块1直流母线2电压高";
			this.Filter1_F1_MVS_2_H.DisplayName = "F1_MVS_2_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString19 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString19.Text = "模块1直流母线2电压高";
			this.Filter1_F1_MVS_2_H.DynamicString = DynamicString19;
			this.Filter1_F1_MVS_2_H.EnableDistribution = false;
			this.Filter1_F1_MVS_2_H.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_MVS_2_H.GroupName = "Filter1";
			this.Filter1_F1_MVS_2_H.History = true;
			this.Filter1_F1_MVS_2_H.IsDigitalValue = false;
			this.Filter1_F1_MVS_2_H.Name = "Filter1_F1_MVS_2_H";
			this.Filter1_F1_MVS_2_H.OutputDevices = null;
			this.Filter1_F1_MVS_2_H.RepeatCount = false;
			this.Filter1_F1_MVS_2_H.TriggerValue = 1;
			this.Filter1_F1_MVS_2_L.AcknowledgeRequired = true;
			this.Filter1_F1_MVS_2_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter1_F1_MVS_2_L.Contacts = null;
			this.Filter1_F1_MVS_2_L.DefaultText = "模块1直流母线2电压低";
			this.Filter1_F1_MVS_2_L.DisplayName = "F1_MVS_2_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString20 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString20.Text = "模块1直流母线2电压低";
			this.Filter1_F1_MVS_2_L.DynamicString = DynamicString20;
			this.Filter1_F1_MVS_2_L.EnableDistribution = false;
			this.Filter1_F1_MVS_2_L.GroupId = new System.Guid("39754837-e7a6-419b-885c-96247728151e");
			this.Filter1_F1_MVS_2_L.GroupName = "Filter1";
			this.Filter1_F1_MVS_2_L.History = true;
			this.Filter1_F1_MVS_2_L.IsDigitalValue = false;
			this.Filter1_F1_MVS_2_L.Name = "Filter1_F1_MVS_2_L";
			this.Filter1_F1_MVS_2_L.OutputDevices = null;
			this.Filter1_F1_MVS_2_L.RepeatCount = false;
			this.Filter1_F1_MVS_2_L.TriggerValue = 1;
			this.Filter1.AlarmItems.Add(this.Filter1_F1_111);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_112);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_113);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_DS_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_VS_A_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_VS_A_L);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_VS_B_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_VS_B_L);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_VS_C_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_VS_C_L);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_FS_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_FS_L);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_TS_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_CS_A_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_CS_B_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_CS_C_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_MVS_1_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_MVS_1_L);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_MVS_2_H);
			this.Filter1.AlarmItems.Add(this.Filter1_F1_MVS_2_L);
			this.Filter1.EnableDistribution = false;
			this.Filter1.InactiveBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(204)))), ((int)(((byte)(71)))));
			this.Filter1.InactiveForeColor = System.Drawing.Color.Black;
			this.Filter1.Name = "Filter1";
			this.Filter1.NormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76)))));
			this.Filter1.NormalForeColor = System.Drawing.Color.Black;
			this.Filter2.AcknowledgeBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(14)))));
			this.Filter2.AcknowledgeForeColor = System.Drawing.Color.Black;
			this.Filter2.ActiveBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(19)))), ((int)(((byte)(41)))));
			this.Filter2.ActiveForeColor = System.Drawing.Color.Black;
			this.Filter2_F2_111.AcknowledgeRequired = true;
			this.Filter2_F2_111.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_111.Contacts = null;
			this.Filter2_F2_111.DefaultText = "模块2A相igbt故障";
			this.Filter2_F2_111.DisplayName = "F2_111";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString21 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString21.Text = "模块2A相igbt故障";
			this.Filter2_F2_111.DynamicString = DynamicString21;
			this.Filter2_F2_111.EnableDistribution = false;
			this.Filter2_F2_111.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_111.GroupName = "Filter2";
			this.Filter2_F2_111.History = true;
			this.Filter2_F2_111.IsDigitalValue = false;
			this.Filter2_F2_111.Name = "Filter2_F2_111";
			this.Filter2_F2_111.OutputDevices = null;
			this.Filter2_F2_111.RepeatCount = false;
			this.Filter2_F2_111.TriggerValue = 1;
			this.Filter2_F2_112.AcknowledgeRequired = true;
			this.Filter2_F2_112.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_112.Contacts = null;
			this.Filter2_F2_112.DefaultText = "模块2B相igbt故障";
			this.Filter2_F2_112.DisplayName = "F2_112";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString22 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString22.Text = "模块2B相igbt故障";
			this.Filter2_F2_112.DynamicString = DynamicString22;
			this.Filter2_F2_112.EnableDistribution = false;
			this.Filter2_F2_112.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_112.GroupName = "Filter2";
			this.Filter2_F2_112.History = true;
			this.Filter2_F2_112.IsDigitalValue = false;
			this.Filter2_F2_112.Name = "Filter2_F2_112";
			this.Filter2_F2_112.OutputDevices = null;
			this.Filter2_F2_112.RepeatCount = false;
			this.Filter2_F2_112.TriggerValue = 1;
			this.Filter2_F2_113.AcknowledgeRequired = true;
			this.Filter2_F2_113.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_113.Contacts = null;
			this.Filter2_F2_113.DefaultText = "模块2C相igbt故障";
			this.Filter2_F2_113.DisplayName = "F2_113";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString23 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString23.Text = "模块2C相igbt故障";
			this.Filter2_F2_113.DynamicString = DynamicString23;
			this.Filter2_F2_113.EnableDistribution = false;
			this.Filter2_F2_113.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_113.GroupName = "Filter2";
			this.Filter2_F2_113.History = true;
			this.Filter2_F2_113.IsDigitalValue = false;
			this.Filter2_F2_113.Name = "Filter2_F2_113";
			this.Filter2_F2_113.OutputDevices = null;
			this.Filter2_F2_113.RepeatCount = false;
			this.Filter2_F2_113.TriggerValue = 1;
			this.Filter2_F2_DS_H.AcknowledgeRequired = true;
			this.Filter2_F2_DS_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_DS_H.Contacts = null;
			this.Filter2_F2_DS_H.DefaultText = "模块2三相不平衡";
			this.Filter2_F2_DS_H.DisplayName = "F2_DS_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString24 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString24.Text = "模块2三相不平衡";
			this.Filter2_F2_DS_H.DynamicString = DynamicString24;
			this.Filter2_F2_DS_H.EnableDistribution = false;
			this.Filter2_F2_DS_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_DS_H.GroupName = "Filter2";
			this.Filter2_F2_DS_H.History = true;
			this.Filter2_F2_DS_H.IsDigitalValue = false;
			this.Filter2_F2_DS_H.Name = "Filter2_F2_DS_H";
			this.Filter2_F2_DS_H.OutputDevices = null;
			this.Filter2_F2_DS_H.RepeatCount = false;
			this.Filter2_F2_DS_H.TriggerValue = 1;
			this.Filter2_F2_VS_A_H.AcknowledgeRequired = true;
			this.Filter2_F2_VS_A_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_VS_A_H.Contacts = null;
			this.Filter2_F2_VS_A_H.DefaultText = "模块2电压高";
			this.Filter2_F2_VS_A_H.DisplayName = "F2_VS_A_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString25 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString25.Text = "模块2电压高";
			this.Filter2_F2_VS_A_H.DynamicString = DynamicString25;
			this.Filter2_F2_VS_A_H.EnableDistribution = false;
			this.Filter2_F2_VS_A_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_VS_A_H.GroupName = "Filter2";
			this.Filter2_F2_VS_A_H.History = true;
			this.Filter2_F2_VS_A_H.IsDigitalValue = false;
			this.Filter2_F2_VS_A_H.Name = "Filter2_F2_VS_A_H";
			this.Filter2_F2_VS_A_H.OutputDevices = null;
			this.Filter2_F2_VS_A_H.RepeatCount = false;
			this.Filter2_F2_VS_A_H.TriggerValue = 1;
			this.Filter2_F2_VS_A_L.AcknowledgeRequired = true;
			this.Filter2_F2_VS_A_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_VS_A_L.Contacts = null;
			this.Filter2_F2_VS_A_L.DefaultText = "模块2电压低";
			this.Filter2_F2_VS_A_L.DisplayName = "F2_VS_A_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString26 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString26.Text = "模块2电压低";
			this.Filter2_F2_VS_A_L.DynamicString = DynamicString26;
			this.Filter2_F2_VS_A_L.EnableDistribution = false;
			this.Filter2_F2_VS_A_L.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_VS_A_L.GroupName = "Filter2";
			this.Filter2_F2_VS_A_L.History = true;
			this.Filter2_F2_VS_A_L.IsDigitalValue = false;
			this.Filter2_F2_VS_A_L.Name = "Filter2_F2_VS_A_L";
			this.Filter2_F2_VS_A_L.OutputDevices = null;
			this.Filter2_F2_VS_A_L.RepeatCount = false;
			this.Filter2_F2_VS_A_L.TriggerValue = 1;
			this.Filter2_F2_VS_B_H.AcknowledgeRequired = true;
			this.Filter2_F2_VS_B_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_VS_B_H.Contacts = null;
			this.Filter2_F2_VS_B_H.DefaultText = "模块2B相电压高";
			this.Filter2_F2_VS_B_H.DisplayName = "F2_VS_B_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString27 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString27.Text = "模块2B相电压高";
			this.Filter2_F2_VS_B_H.DynamicString = DynamicString27;
			this.Filter2_F2_VS_B_H.EnableDistribution = false;
			this.Filter2_F2_VS_B_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_VS_B_H.GroupName = "Filter2";
			this.Filter2_F2_VS_B_H.History = true;
			this.Filter2_F2_VS_B_H.IsDigitalValue = false;
			this.Filter2_F2_VS_B_H.Name = "Filter2_F2_VS_B_H";
			this.Filter2_F2_VS_B_H.OutputDevices = null;
			this.Filter2_F2_VS_B_H.RepeatCount = false;
			this.Filter2_F2_VS_B_H.TriggerValue = 1;
			this.Filter2_F2_VS_B_L.AcknowledgeRequired = true;
			this.Filter2_F2_VS_B_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_VS_B_L.Contacts = null;
			this.Filter2_F2_VS_B_L.DefaultText = "模块2B相电压低";
			this.Filter2_F2_VS_B_L.DisplayName = "F2_VS_B_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString28 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString28.Text = "模块2B相电压低";
			this.Filter2_F2_VS_B_L.DynamicString = DynamicString28;
			this.Filter2_F2_VS_B_L.EnableDistribution = false;
			this.Filter2_F2_VS_B_L.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_VS_B_L.GroupName = "Filter2";
			this.Filter2_F2_VS_B_L.History = true;
			this.Filter2_F2_VS_B_L.IsDigitalValue = false;
			this.Filter2_F2_VS_B_L.Name = "Filter2_F2_VS_B_L";
			this.Filter2_F2_VS_B_L.OutputDevices = null;
			this.Filter2_F2_VS_B_L.RepeatCount = false;
			this.Filter2_F2_VS_B_L.TriggerValue = 1;
			this.Filter2_F2_VS_C_H.AcknowledgeRequired = true;
			this.Filter2_F2_VS_C_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_VS_C_H.Contacts = null;
			this.Filter2_F2_VS_C_H.DefaultText = "模块2C相电压高";
			this.Filter2_F2_VS_C_H.DisplayName = "F2_VS_C_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString29 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString29.Text = "模块2C相电压高";
			this.Filter2_F2_VS_C_H.DynamicString = DynamicString29;
			this.Filter2_F2_VS_C_H.EnableDistribution = false;
			this.Filter2_F2_VS_C_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_VS_C_H.GroupName = "Filter2";
			this.Filter2_F2_VS_C_H.History = true;
			this.Filter2_F2_VS_C_H.IsDigitalValue = false;
			this.Filter2_F2_VS_C_H.Name = "Filter2_F2_VS_C_H";
			this.Filter2_F2_VS_C_H.OutputDevices = null;
			this.Filter2_F2_VS_C_H.RepeatCount = false;
			this.Filter2_F2_VS_C_H.TriggerValue = 1;
			this.Filter2_F2_VS_C_L.AcknowledgeRequired = true;
			this.Filter2_F2_VS_C_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_VS_C_L.Contacts = null;
			this.Filter2_F2_VS_C_L.DefaultText = "模块2C相电压低";
			this.Filter2_F2_VS_C_L.DisplayName = "F2_VS_C_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString30 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString30.Text = "模块2C相电压低";
			this.Filter2_F2_VS_C_L.DynamicString = DynamicString30;
			this.Filter2_F2_VS_C_L.EnableDistribution = false;
			this.Filter2_F2_VS_C_L.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_VS_C_L.GroupName = "Filter2";
			this.Filter2_F2_VS_C_L.History = true;
			this.Filter2_F2_VS_C_L.IsDigitalValue = false;
			this.Filter2_F2_VS_C_L.Name = "Filter2_F2_VS_C_L";
			this.Filter2_F2_VS_C_L.OutputDevices = null;
			this.Filter2_F2_VS_C_L.RepeatCount = false;
			this.Filter2_F2_VS_C_L.TriggerValue = 1;
			this.Filter2_F2_FS_H.AcknowledgeRequired = true;
			this.Filter2_F2_FS_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_FS_H.Contacts = null;
			this.Filter2_F2_FS_H.DefaultText = "模块2频率高";
			this.Filter2_F2_FS_H.DisplayName = "F2_FS_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString31 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString31.Text = "模块2频率高";
			this.Filter2_F2_FS_H.DynamicString = DynamicString31;
			this.Filter2_F2_FS_H.EnableDistribution = false;
			this.Filter2_F2_FS_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_FS_H.GroupName = "Filter2";
			this.Filter2_F2_FS_H.History = true;
			this.Filter2_F2_FS_H.IsDigitalValue = false;
			this.Filter2_F2_FS_H.Name = "Filter2_F2_FS_H";
			this.Filter2_F2_FS_H.OutputDevices = null;
			this.Filter2_F2_FS_H.RepeatCount = false;
			this.Filter2_F2_FS_H.TriggerValue = 1;
			this.Filter2_F2_FS_L.AcknowledgeRequired = true;
			this.Filter2_F2_FS_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_FS_L.Contacts = null;
			this.Filter2_F2_FS_L.DefaultText = "模块2频率低";
			this.Filter2_F2_FS_L.DisplayName = "F2_FS_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString32 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString32.Text = "模块2频率低";
			this.Filter2_F2_FS_L.DynamicString = DynamicString32;
			this.Filter2_F2_FS_L.EnableDistribution = false;
			this.Filter2_F2_FS_L.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_FS_L.GroupName = "Filter2";
			this.Filter2_F2_FS_L.History = true;
			this.Filter2_F2_FS_L.IsDigitalValue = false;
			this.Filter2_F2_FS_L.Name = "Filter2_F2_FS_L";
			this.Filter2_F2_FS_L.OutputDevices = null;
			this.Filter2_F2_FS_L.RepeatCount = false;
			this.Filter2_F2_FS_L.TriggerValue = 1;
			this.Filter2_F2_TS_H.AcknowledgeRequired = true;
			this.Filter2_F2_TS_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_TS_H.Contacts = null;
			this.Filter2_F2_TS_H.DefaultText = "模块2温度高";
			this.Filter2_F2_TS_H.DisplayName = "F2_TS_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString33 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString33.Text = "模块2温度高";
			this.Filter2_F2_TS_H.DynamicString = DynamicString33;
			this.Filter2_F2_TS_H.EnableDistribution = false;
			this.Filter2_F2_TS_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_TS_H.GroupName = "Filter2";
			this.Filter2_F2_TS_H.History = true;
			this.Filter2_F2_TS_H.IsDigitalValue = false;
			this.Filter2_F2_TS_H.Name = "Filter2_F2_TS_H";
			this.Filter2_F2_TS_H.OutputDevices = null;
			this.Filter2_F2_TS_H.RepeatCount = false;
			this.Filter2_F2_TS_H.TriggerValue = 1;
			this.Filter2_F2_CS_A_H.AcknowledgeRequired = true;
			this.Filter2_F2_CS_A_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_CS_A_H.Contacts = null;
			this.Filter2_F2_CS_A_H.DefaultText = "模块2A相输出电流高";
			this.Filter2_F2_CS_A_H.DisplayName = "F2_CS_A_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString34 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString34.Text = "模块2A相输出电流高";
			this.Filter2_F2_CS_A_H.DynamicString = DynamicString34;
			this.Filter2_F2_CS_A_H.EnableDistribution = false;
			this.Filter2_F2_CS_A_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_CS_A_H.GroupName = "Filter2";
			this.Filter2_F2_CS_A_H.History = true;
			this.Filter2_F2_CS_A_H.IsDigitalValue = false;
			this.Filter2_F2_CS_A_H.Name = "Filter2_F2_CS_A_H";
			this.Filter2_F2_CS_A_H.OutputDevices = null;
			this.Filter2_F2_CS_A_H.RepeatCount = false;
			this.Filter2_F2_CS_A_H.TriggerValue = 1;
			this.Filter2_F2_CS_B_H.AcknowledgeRequired = true;
			this.Filter2_F2_CS_B_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_CS_B_H.Contacts = null;
			this.Filter2_F2_CS_B_H.DefaultText = "模块2B相输出电流高";
			this.Filter2_F2_CS_B_H.DisplayName = "F2_CS_B_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString35 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString35.Text = "模块2B相输出电流高";
			this.Filter2_F2_CS_B_H.DynamicString = DynamicString35;
			this.Filter2_F2_CS_B_H.EnableDistribution = false;
			this.Filter2_F2_CS_B_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_CS_B_H.GroupName = "Filter2";
			this.Filter2_F2_CS_B_H.History = true;
			this.Filter2_F2_CS_B_H.IsDigitalValue = false;
			this.Filter2_F2_CS_B_H.Name = "Filter2_F2_CS_B_H";
			this.Filter2_F2_CS_B_H.OutputDevices = null;
			this.Filter2_F2_CS_B_H.RepeatCount = false;
			this.Filter2_F2_CS_B_H.TriggerValue = 1;
			this.Filter2_F2_CS_C_H.AcknowledgeRequired = true;
			this.Filter2_F2_CS_C_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_CS_C_H.Contacts = null;
			this.Filter2_F2_CS_C_H.DefaultText = "模块2C相输出电流高";
			this.Filter2_F2_CS_C_H.DisplayName = "F2_CS_C_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString36 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString36.Text = "模块2C相输出电流高";
			this.Filter2_F2_CS_C_H.DynamicString = DynamicString36;
			this.Filter2_F2_CS_C_H.EnableDistribution = false;
			this.Filter2_F2_CS_C_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_CS_C_H.GroupName = "Filter2";
			this.Filter2_F2_CS_C_H.History = true;
			this.Filter2_F2_CS_C_H.IsDigitalValue = false;
			this.Filter2_F2_CS_C_H.Name = "Filter2_F2_CS_C_H";
			this.Filter2_F2_CS_C_H.OutputDevices = null;
			this.Filter2_F2_CS_C_H.RepeatCount = false;
			this.Filter2_F2_CS_C_H.TriggerValue = 1;
			this.Filter2_F2_MVS_1_H.AcknowledgeRequired = true;
			this.Filter2_F2_MVS_1_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_MVS_1_H.Contacts = null;
			this.Filter2_F2_MVS_1_H.DefaultText = "模块2直流母线1电压高";
			this.Filter2_F2_MVS_1_H.DisplayName = "F2_MVS_1_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString37 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString37.Text = "模块2直流母线1电压高";
			this.Filter2_F2_MVS_1_H.DynamicString = DynamicString37;
			this.Filter2_F2_MVS_1_H.EnableDistribution = false;
			this.Filter2_F2_MVS_1_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_MVS_1_H.GroupName = "Filter2";
			this.Filter2_F2_MVS_1_H.History = true;
			this.Filter2_F2_MVS_1_H.IsDigitalValue = false;
			this.Filter2_F2_MVS_1_H.Name = "Filter2_F2_MVS_1_H";
			this.Filter2_F2_MVS_1_H.OutputDevices = null;
			this.Filter2_F2_MVS_1_H.RepeatCount = false;
			this.Filter2_F2_MVS_1_H.TriggerValue = 1;
			this.Filter2_F2_MVS_1_L.AcknowledgeRequired = true;
			this.Filter2_F2_MVS_1_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_MVS_1_L.Contacts = null;
			this.Filter2_F2_MVS_1_L.DefaultText = "模块2直流母线1电压低";
			this.Filter2_F2_MVS_1_L.DisplayName = "F2_MVS_1_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString38 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString38.Text = "模块2直流母线1电压低";
			this.Filter2_F2_MVS_1_L.DynamicString = DynamicString38;
			this.Filter2_F2_MVS_1_L.EnableDistribution = false;
			this.Filter2_F2_MVS_1_L.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_MVS_1_L.GroupName = "Filter2";
			this.Filter2_F2_MVS_1_L.History = true;
			this.Filter2_F2_MVS_1_L.IsDigitalValue = false;
			this.Filter2_F2_MVS_1_L.Name = "Filter2_F2_MVS_1_L";
			this.Filter2_F2_MVS_1_L.OutputDevices = null;
			this.Filter2_F2_MVS_1_L.RepeatCount = false;
			this.Filter2_F2_MVS_1_L.TriggerValue = 1;
			this.Filter2_F2_MVS_2_H.AcknowledgeRequired = true;
			this.Filter2_F2_MVS_2_H.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_MVS_2_H.Contacts = null;
			this.Filter2_F2_MVS_2_H.DefaultText = "模块2直流母线2电压高";
			this.Filter2_F2_MVS_2_H.DisplayName = "F2_MVS_2_H";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString39 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString39.Text = "模块2直流母线2电压高";
			this.Filter2_F2_MVS_2_H.DynamicString = DynamicString39;
			this.Filter2_F2_MVS_2_H.EnableDistribution = false;
			this.Filter2_F2_MVS_2_H.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_MVS_2_H.GroupName = "Filter2";
			this.Filter2_F2_MVS_2_H.History = true;
			this.Filter2_F2_MVS_2_H.IsDigitalValue = false;
			this.Filter2_F2_MVS_2_H.Name = "Filter2_F2_MVS_2_H";
			this.Filter2_F2_MVS_2_H.OutputDevices = null;
			this.Filter2_F2_MVS_2_H.RepeatCount = false;
			this.Filter2_F2_MVS_2_H.TriggerValue = 1;
			this.Filter2_F2_MVS_2_L.AcknowledgeRequired = true;
			this.Filter2_F2_MVS_2_L.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Filter2_F2_MVS_2_L.Contacts = null;
			this.Filter2_F2_MVS_2_L.DefaultText = "模块2直流母线2电压低";
			this.Filter2_F2_MVS_2_L.DisplayName = "F2_MVS_2_L";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString40 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString40.Text = "模块2直流母线2电压低";
			this.Filter2_F2_MVS_2_L.DynamicString = DynamicString40;
			this.Filter2_F2_MVS_2_L.EnableDistribution = false;
			this.Filter2_F2_MVS_2_L.GroupId = new System.Guid("aab4fd7f-0877-4ae8-8e38-dcd4898a1d6b");
			this.Filter2_F2_MVS_2_L.GroupName = "Filter2";
			this.Filter2_F2_MVS_2_L.History = true;
			this.Filter2_F2_MVS_2_L.IsDigitalValue = false;
			this.Filter2_F2_MVS_2_L.Name = "Filter2_F2_MVS_2_L";
			this.Filter2_F2_MVS_2_L.OutputDevices = null;
			this.Filter2_F2_MVS_2_L.RepeatCount = false;
			this.Filter2_F2_MVS_2_L.TriggerValue = 1;
			this.Filter2.AlarmItems.Add(this.Filter2_F2_111);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_112);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_113);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_DS_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_VS_A_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_VS_A_L);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_VS_B_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_VS_B_L);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_VS_C_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_VS_C_L);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_FS_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_FS_L);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_TS_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_CS_A_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_CS_B_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_CS_C_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_MVS_1_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_MVS_1_L);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_MVS_2_H);
			this.Filter2.AlarmItems.Add(this.Filter2_F2_MVS_2_L);
			this.Filter2.EnableDistribution = false;
			this.Filter2.InactiveBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(204)))), ((int)(((byte)(71)))));
			this.Filter2.InactiveForeColor = System.Drawing.Color.Black;
			this.Filter2.Name = "Filter2";
			this.Filter2.NormalBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76)))));
			this.Filter2.NormalForeColor = System.Drawing.Color.Black;
			this.AlarmGroups.Add(this.Filter1);
			this.AlarmGroups.Add(this.Filter2);
			this.StorageEvent.AcknowledgeTime = null;
			this.StorageEvent.ActiveTime = null;
			this.StorageEvent.AlarmGroupName = "";
			this.StorageEvent.AlarmGroupText = "";
			this.StorageEvent.AlarmItemId = new System.Guid("00000000-0000-0000-0000-000000000000");
			this.StorageEvent.Count = 0;
			this.StorageEvent.DisplayText = "";
			this.StorageEvent.EnableDistribution = false;
			this.StorageEvent.ForceToList = false;
			this.StorageEvent.History = false;
			this.StorageEvent.InActiveTime = null;
			this.StorageEvent.NormalTime = null;
			this.StorageEvent.RepeatCount = false;
			this.StorageEvent.State = Neo.ApplicationFramework.Interfaces.AlarmState.Normal;
			this.StorageEvent.TableName = "AlarmServer";
			this.StorageEvent.Text = "";
		}
		
		private void Filter1_Action_AlarmActive(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Filter1", "AlarmActive", "Set Tag", "Tags.buzzer", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.buzzer.SetTag();
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Filter1", "AlarmActive", "Set Tag", "Tags.flickerState", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.flickerState.SetTag();
		}
		
		private void Filter2_Action_AlarmActive(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Filter2", "AlarmActive", "Set Tag", "Tags.buzzer", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.buzzer.SetTag();
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Filter2", "AlarmActive", "Set Tag", "Tags.flickerState", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.flickerState.SetTag();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(AlarmServer));
			this.m_Filter1.Text = resources.GetText("AlarmServer.Filter1.Text", "Filter1");
			this.m_Filter2.Text = resources.GetText("AlarmServer.Filter2.Text", "Filter2");
			this.m_Filter1_F1_111.StaticText = resources.GetText("AlarmServer.Filter1_F1_111.StaticText", "模块1A相igbt故障");
			this.m_Filter1_F1_112.StaticText = resources.GetText("AlarmServer.Filter1_F1_112.StaticText", "模块1B相igbt故障");
			this.m_Filter1_F1_113.StaticText = resources.GetText("AlarmServer.Filter1_F1_113.StaticText", "模块1C相igbt故障");
			this.m_Filter2_F2_111.StaticText = resources.GetText("AlarmServer.Filter2_F2_111.StaticText", "模块2A相igbt故障");
			this.m_Filter2_F2_112.StaticText = resources.GetText("AlarmServer.Filter2_F2_112.StaticText", "模块2B相igbt故障");
			this.m_Filter2_F2_113.StaticText = resources.GetText("AlarmServer.Filter2_F2_113.StaticText", "模块2C相igbt故障");
			this.m_Filter1_F1_DS_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_DS_H.StaticText", "模块1三相不平衡");
			this.m_Filter1_F1_VS_A_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_VS_A_H.StaticText", "模块1电压高");
			this.m_Filter1_F1_VS_A_L.StaticText = resources.GetText("AlarmServer.Filter1_F1_VS_A_L.StaticText", "模块1电压低");
			this.m_Filter1_F1_VS_B_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_VS_B_H.StaticText", "模块1B相电压高");
			this.m_Filter1_F1_VS_B_L.StaticText = resources.GetText("AlarmServer.Filter1_F1_VS_B_L.StaticText", "模块1B相电压低");
			this.m_Filter1_F1_VS_C_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_VS_C_H.StaticText", "模块1C相电压高");
			this.m_Filter1_F1_VS_C_L.StaticText = resources.GetText("AlarmServer.Filter1_F1_VS_C_L.StaticText", "模块1C相电压低");
			this.m_Filter1_F1_FS_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_FS_H.StaticText", "模块1频率高");
			this.m_Filter1_F1_FS_L.StaticText = resources.GetText("AlarmServer.Filter1_F1_FS_L.StaticText", "模块1频率低");
			this.m_Filter1_F1_TS_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_TS_H.StaticText", "模块1温度高");
			this.m_Filter1_F1_CS_A_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_CS_A_H.StaticText", "模块1A相输出电流高");
			this.m_Filter1_F1_CS_B_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_CS_B_H.StaticText", "模块1B相输出电流高");
			this.m_Filter1_F1_CS_C_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_CS_C_H.StaticText", "模块1C相输出电流高");
			this.m_Filter1_F1_MVS_1_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_MVS_1_H.StaticText", "模块1直流母线1电压高");
			this.m_Filter1_F1_MVS_1_L.StaticText = resources.GetText("AlarmServer.Filter1_F1_MVS_1_L.StaticText", "模块1直流母线1电压低");
			this.m_Filter1_F1_MVS_2_H.StaticText = resources.GetText("AlarmServer.Filter1_F1_MVS_2_H.StaticText", "模块1直流母线2电压高");
			this.m_Filter1_F1_MVS_2_L.StaticText = resources.GetText("AlarmServer.Filter1_F1_MVS_2_L.StaticText", "模块1直流母线2电压低");
			this.m_Filter2_F2_DS_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_DS_H.StaticText", "模块2三相不平衡");
			this.m_Filter2_F2_VS_A_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_VS_A_H.StaticText", "模块2电压高");
			this.m_Filter2_F2_VS_A_L.StaticText = resources.GetText("AlarmServer.Filter2_F2_VS_A_L.StaticText", "模块2电压低");
			this.m_Filter2_F2_VS_B_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_VS_B_H.StaticText", "模块2B相电压高");
			this.m_Filter2_F2_VS_B_L.StaticText = resources.GetText("AlarmServer.Filter2_F2_VS_B_L.StaticText", "模块2B相电压低");
			this.m_Filter2_F2_VS_C_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_VS_C_H.StaticText", "模块2C相电压高");
			this.m_Filter2_F2_VS_C_L.StaticText = resources.GetText("AlarmServer.Filter2_F2_VS_C_L.StaticText", "模块2C相电压低");
			this.m_Filter2_F2_FS_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_FS_H.StaticText", "模块2频率高");
			this.m_Filter2_F2_FS_L.StaticText = resources.GetText("AlarmServer.Filter2_F2_FS_L.StaticText", "模块2频率低");
			this.m_Filter2_F2_TS_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_TS_H.StaticText", "模块2温度高");
			this.m_Filter2_F2_CS_A_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_CS_A_H.StaticText", "模块2A相输出电流高");
			this.m_Filter2_F2_CS_B_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_CS_B_H.StaticText", "模块2B相输出电流高");
			this.m_Filter2_F2_CS_C_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_CS_C_H.StaticText", "模块2C相输出电流高");
			this.m_Filter2_F2_MVS_1_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_MVS_1_H.StaticText", "模块2直流母线1电压高");
			this.m_Filter2_F2_MVS_1_L.StaticText = resources.GetText("AlarmServer.Filter2_F2_MVS_1_L.StaticText", "模块2直流母线1电压低");
			this.m_Filter2_F2_MVS_2_H.StaticText = resources.GetText("AlarmServer.Filter2_F2_MVS_2_H.StaticText", "模块2直流母线2电压高");
			this.m_Filter2_F2_MVS_2_L.StaticText = resources.GetText("AlarmServer.Filter2_F2_MVS_2_L.StaticText", "模块2直流母线2电压低");
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
