//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class BG : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Alarm.AlarmViewer m_AlarmViewer;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock1;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button7;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button9;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private bool m_Initialized_BG;
        
        public BG() {
            this.InitializeComponent();
            this.m_Button4.Click += new System.EventHandler(this.m_Button4_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button8.Click += new System.EventHandler(this.m_Button8_Action_Click);
            this.m_Button7.Click += new System.EventHandler(this.m_Button7_Action_Click);
            this.m_Button9.Click += new System.EventHandler(this.m_Button9_Action_Click);
            this.m_Button3.Click += new System.EventHandler(this.m_Button3_Action_Click);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        public Neo.ApplicationFramework.Controls.Script.AlarmViewerCFAdapter AlarmViewer {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AlarmViewerCFAdapter>(this.m_AlarmViewer);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Controls.Logic.AlarmEventFilter alarmeventfilter1 = new Neo.ApplicationFramework.Controls.Logic.AlarmEventFilter();
            Neo.ApplicationFramework.Controls.Logic.AlarmEventFilterGroup alarmeventfiltergroup1 = new Neo.ApplicationFramework.Controls.Logic.AlarmEventFilterGroup();
            Neo.ApplicationFramework.Controls.Logic.AlarmEventFilterGroup alarmeventfiltergroup2 = new Neo.ApplicationFramework.Controls.Logic.AlarmEventFilterGroup();
            Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo alarmcolumninfo1 = new Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo();
            Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo alarmcolumninfo2 = new Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf5 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf6 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf7 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf8 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf5 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf9 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf10 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf6 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf11 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf12 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf7 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf13 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf14 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_AlarmViewer = new Neo.ApplicationFramework.Controls.Alarm.AlarmViewer();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_DigitalClock1 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DigitalClock2 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_Button8 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button7 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button9 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture5 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_AlarmViewer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            this.SuspendLayout();
            // 
            // BG
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(73)))), ((int)(((byte)(104))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_AlarmViewer
            // 
            this.m_AlarmViewer.AcknowledgeAllButtonIsVisible = false;
            this.m_AlarmViewer.AcknowledgeSelectedButtonIsVisible = false;
            alarmeventfiltergroup1.Enabled = true;
            alarmeventfiltergroup1.Name = "Filter1";
            alarmeventfiltergroup1.ShowAcknowlegedAlarms = true;
            alarmeventfiltergroup1.ShowActiveAlarms = true;
            alarmeventfiltergroup1.ShowInactiveAlarms = true;
            alarmeventfiltergroup1.ShowNormalAlarms = true;
            alarmeventfiltergroup2.Enabled = true;
            alarmeventfiltergroup2.Name = "Filter2";
            alarmeventfiltergroup2.ShowAcknowlegedAlarms = true;
            alarmeventfiltergroup2.ShowActiveAlarms = true;
            alarmeventfiltergroup2.ShowInactiveAlarms = true;
            alarmeventfiltergroup2.ShowNormalAlarms = true;
            alarmeventfilter1.Groups.Add(alarmeventfiltergroup1);
            alarmeventfilter1.Groups.Add(alarmeventfiltergroup2);
            alarmeventfilter1.MaximumAlarmRows = 200;
            this.m_AlarmViewer.AlarmEventFilter = alarmeventfilter1;
            this.m_AlarmViewer.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.ButtonBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.ButtonHeight = 40;
            this.m_AlarmViewer.ButtonWidth = 130;
            this.m_AlarmViewer.ClearButtonIsVisible = false;
            this.m_AlarmViewer.ColumnHeaderBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(211)))), ((int)(((byte)(211)))), ((int)(((byte)(211))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.ColumnHeadersVisible = false;
            this.m_AlarmViewer.ContextMenusEnabled = false;
            this.m_AlarmViewer.EnabledDynamicsValue = true;
            this.m_AlarmViewer.FilterButtonIsVisible = false;
            this.m_AlarmViewer.FontFamily = "微软雅黑";
            this.m_AlarmViewer.FontSizePixels = 12;
            this.m_AlarmViewer.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.GridBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.InfoButtonIsVisible = false;
            this.m_AlarmViewer.Input = false;
            this.m_AlarmViewer.Location = new System.Drawing.Point(101, 10);
            this.m_AlarmViewer.MaximumAlarmViewerRows = 200;
            this.m_AlarmViewer.Name = "m_AlarmViewer";
            this.m_AlarmViewer.PauseButtonIsVisible = false;
            this.m_AlarmViewer.ScreenOwnerName = "BG";
            this.m_AlarmViewer.Size = new System.Drawing.Size(495, 68);
            this.m_AlarmViewer.SummaryRowVisible = false;
            this.m_AlarmViewer.TabIndex = 2147483647;
            alarmcolumninfo1.ColumnWidth = 100D;
            alarmcolumninfo1.HeaderName = "Active Time";
            alarmcolumninfo1.MappingName = "ActiveTime";
            alarmcolumninfo2.ColumnWidth = 370D;
            alarmcolumninfo2.HeaderName = "Text";
            alarmcolumninfo2.MappingName = "DisplayText";
            this.m_AlarmViewer.VisibleColumns = new Neo.ApplicationFramework.Interfaces.IColumnInfo[] {
                    ((Neo.ApplicationFramework.Interfaces.IColumnInfo)(alarmcolumninfo1)),
                    ((Neo.ApplicationFramework.Interfaces.IColumnInfo)(alarmcolumninfo2))};
            this.m_AlarmViewer.VisibleDynamicsValue = true;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontFamily = "微软雅黑";
            this.m_Button4.FontSizePixels = 14;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122)))));
            this.m_Button4.Height = 42;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 482;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "BG";
            this.m_Button4.StyleName = "Glossy";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button4.TextHeight = 20;
            stringintervalmappercf1.DefaultValue = "SETTING";
            stringintervalcf1.Value = "综合设置";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "SETTING";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            this.m_Button4.TextIntervalMapper = stringintervalmappercf1;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 145;
            this.m_Button4.Top = 439;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = 2055473836;
            this.m_Button4.Width = 151;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(109)))), ((int)(((byte)(157))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 84;
            this.m_Rectangle.Left = 1;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "BG";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Top = 0;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 798;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "微软雅黑";
            this.m_Button1.FontSizePixels = 15;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button1.Height = 68;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 712;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "BG";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 20;
            stringintervalmappercf2.DefaultValue = "MUTE";
            stringintervalcf3.Value = "消音";
            stringintervalcf4.End = 1D;
            stringintervalcf4.Start = 1D;
            stringintervalcf4.Value = "MUTE";
            stringintervalmappercf2.Intervals.Add(stringintervalcf3);
            stringintervalmappercf2.Intervals.Add(stringintervalcf4);
            this.m_Button1.TextIntervalMapper = stringintervalmappercf2;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 71;
            this.m_Button1.Top = 10;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -1469566138;
            this.m_Button1.Width = 77;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(106)))), ((int)(((byte)(46))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "微软雅黑";
            this.m_Button.FontSizePixels = 15;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 68;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 627;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "BG";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button.TextHeight = 20;
            stringintervalmappercf3.DefaultValue = "ACK";
            stringintervalcf5.Value = "确认";
            stringintervalcf6.End = 1D;
            stringintervalcf6.Start = 1D;
            stringintervalcf6.Value = "ACK";
            stringintervalmappercf3.Intervals.Add(stringintervalcf5);
            stringintervalmappercf3.Intervals.Add(stringintervalcf6);
            this.m_Button.TextIntervalMapper = stringintervalmappercf3;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 71;
            this.m_Button.Top = 10;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = 1870975302;
            this.m_Button.Width = 77;
            // 
            // m_DigitalClock1
            // 
            this.m_DigitalClock1.BlinkDynamicsValue = false;
            this.m_DigitalClock1.DelayMouseInputPeriod = 0;
            this.m_DigitalClock1.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Date;
            this.m_DigitalClock1.EnabledDynamicsValue = true;
            this.m_DigitalClock1.FontSizePixels = 14;
            this.m_DigitalClock1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_DigitalClock1.Height = 18;
            this.m_DigitalClock1.Left = 0;
            this.m_DigitalClock1.Name = "m_DigitalClock1";
            this.m_DigitalClock1.ScreenOwnerName = "BG";
            this.m_DigitalClock1.ShowDayOfWeek = false;
            this.m_DigitalClock1.ShowSeconds = true;
            this.m_DigitalClock1.Text = "2020/4/7 星期二";
            this.m_DigitalClock1.Top = 7;
            this.m_DigitalClock1.VisibleDynamicsValue = true;
            this.m_DigitalClock1.Width = 130;
            // 
            // m_DigitalClock2
            // 
            this.m_DigitalClock2.BlinkDynamicsValue = false;
            this.m_DigitalClock2.DelayMouseInputPeriod = 0;
            this.m_DigitalClock2.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Time;
            this.m_DigitalClock2.EnabledDynamicsValue = true;
            this.m_DigitalClock2.FontSizePixels = 14;
            this.m_DigitalClock2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_DigitalClock2.Height = 18;
            this.m_DigitalClock2.Left = 0;
            this.m_DigitalClock2.Name = "m_DigitalClock2";
            this.m_DigitalClock2.ScreenOwnerName = "BG";
            this.m_DigitalClock2.ShowDayOfWeek = false;
            this.m_DigitalClock2.ShowSeconds = true;
            this.m_DigitalClock2.Text = "15:08:09";
            this.m_DigitalClock2.Top = 24;
            this.m_DigitalClock2.VisibleDynamicsValue = true;
            this.m_DigitalClock2.Width = 116;
            // 
            // m_Button8
            // 
            this.m_Button8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BlinkDynamicsValue = false;
            this.m_Button8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button8.DelayMouseInputPeriod = 0;
            this.m_Button8.EnabledDynamicsValue = true;
            this.m_Button8.FontFamily = "微软雅黑";
            this.m_Button8.FontSizePixels = 14;
            this.m_Button8.ForceTransparency = true;
            this.m_Button8.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122)))));
            this.m_Button8.Height = 42;
            this.m_Button8.IndicatorMargin = null;
            this.m_Button8.Left = 164;
            this.m_Button8.Name = "m_Button8";
            this.m_Button8.RequiresTransparency = true;
            this.m_Button8.ScreenOwnerName = "BG";
            this.m_Button8.StyleName = "Glossy";
            this.m_Button8.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button8.TextHeight = 20;
            stringintervalmappercf4.DefaultValue = "INFORMATION";
            stringintervalcf7.Value = "模块详情";
            stringintervalcf8.End = 1D;
            stringintervalcf8.Start = 1D;
            stringintervalcf8.Value = "INFORMATION";
            stringintervalmappercf4.Intervals.Add(stringintervalcf7);
            stringintervalmappercf4.Intervals.Add(stringintervalcf8);
            this.m_Button8.TextIntervalMapper = stringintervalmappercf4;
            this.m_Button8.TextValue = 0D;
            this.m_Button8.TextWidth = 145;
            this.m_Button8.Top = 440;
            this.m_Button8.Value = 0D;
            this.m_Button8.VisibleDynamicsValue = true;
            this.m_Button8.VisualPropertiesHashCode = 2055473836;
            this.m_Button8.Width = 151;
            // 
            // m_Button7
            // 
            this.m_Button7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BlinkDynamicsValue = false;
            this.m_Button7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button7.DelayMouseInputPeriod = 0;
            this.m_Button7.EnabledDynamicsValue = true;
            this.m_Button7.FontFamily = "微软雅黑";
            this.m_Button7.FontSizePixels = 14;
            this.m_Button7.ForceTransparency = true;
            this.m_Button7.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122)))));
            this.m_Button7.Height = 42;
            this.m_Button7.IndicatorMargin = null;
            this.m_Button7.Left = 641;
            this.m_Button7.Name = "m_Button7";
            this.m_Button7.RequiresTransparency = true;
            this.m_Button7.ScreenOwnerName = "BG";
            this.m_Button7.StyleName = "Glossy";
            this.m_Button7.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button7.TextHeight = 20;
            stringintervalmappercf5.DefaultValue = "RUN/STOP";
            stringintervalcf9.Value = "运行/停止";
            stringintervalcf10.End = 1D;
            stringintervalcf10.Start = 1D;
            stringintervalcf10.Value = "RUN/STOP";
            stringintervalmappercf5.Intervals.Add(stringintervalcf9);
            stringintervalmappercf5.Intervals.Add(stringintervalcf10);
            this.m_Button7.TextIntervalMapper = stringintervalmappercf5;
            this.m_Button7.TextValue = 0D;
            this.m_Button7.TextWidth = 133;
            this.m_Button7.Top = 440;
            this.m_Button7.Value = 0D;
            this.m_Button7.VisibleDynamicsValue = true;
            this.m_Button7.VisualPropertiesHashCode = -864662747;
            this.m_Button7.Width = 139;
            // 
            // m_Button9
            // 
            this.m_Button9.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button9.BlinkDynamicsValue = false;
            this.m_Button9.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button9.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button9.DelayMouseInputPeriod = 0;
            this.m_Button9.EnabledDynamicsValue = true;
            this.m_Button9.FontFamily = "微软雅黑";
            this.m_Button9.FontSizePixels = 14;
            this.m_Button9.ForceTransparency = true;
            this.m_Button9.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122)))));
            this.m_Button9.Height = 42;
            this.m_Button9.IndicatorMargin = null;
            this.m_Button9.Left = 17;
            this.m_Button9.Name = "m_Button9";
            this.m_Button9.RequiresTransparency = true;
            this.m_Button9.ScreenOwnerName = "BG";
            this.m_Button9.StyleName = "Glossy";
            this.m_Button9.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button9.TextHeight = 20;
            stringintervalmappercf6.DefaultValue = "HOME";
            stringintervalcf11.Value = "主页";
            stringintervalcf12.End = 1D;
            stringintervalcf12.Start = 1D;
            stringintervalcf12.Value = "HOME";
            stringintervalmappercf6.Intervals.Add(stringintervalcf11);
            stringintervalmappercf6.Intervals.Add(stringintervalcf12);
            this.m_Button9.TextIntervalMapper = stringintervalmappercf6;
            this.m_Button9.TextValue = 0D;
            this.m_Button9.TextWidth = 133;
            this.m_Button9.Top = 440;
            this.m_Button9.Value = 0D;
            this.m_Button9.VisibleDynamicsValue = true;
            this.m_Button9.VisualPropertiesHashCode = -1741837915;
            this.m_Button9.Width = 139;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 38;
            this.m_Picture.Left = 26;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "BG";
            this.m_Picture.SymbolName = "home";
            this.m_Picture.Top = 442;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 38;
            // 
            // m_Picture5
            // 
            this.m_Picture5.BlinkDynamicsValue = false;
            this.m_Picture5.DelayMouseInputPeriod = 0;
            this.m_Picture5.EnabledDynamicsValue = true;
            this.m_Picture5.Height = 42;
            this.m_Picture5.Left = 35;
            this.m_Picture5.Name = "m_Picture5";
            this.m_Picture5.ScreenOwnerName = "BG";
            this.m_Picture5.Stretch = true;
            this.m_Picture5.SymbolName = "driverico";
            this.m_Picture5.Top = 41;
            this.m_Picture5.VisibleDynamicsValue = true;
            this.m_Picture5.Width = 42;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button3.DelayMouseInputPeriod = 0;
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontFamily = "微软雅黑";
            this.m_Button3.FontSizePixels = 14;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122)))));
            this.m_Button3.Height = 42;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 323;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "BG";
            this.m_Button3.StyleName = "Glossy";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button3.TextHeight = 20;
            stringintervalmappercf7.DefaultValue = "USER SETTING";
            stringintervalcf13.Value = "用户设置";
            stringintervalcf14.End = 1D;
            stringintervalcf14.Start = 1D;
            stringintervalcf14.Value = "USER SETTING";
            stringintervalmappercf7.Intervals.Add(stringintervalcf13);
            stringintervalmappercf7.Intervals.Add(stringintervalcf14);
            this.m_Button3.TextIntervalMapper = stringintervalmappercf7;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 145;
            this.m_Button3.Top = 440;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = 2055473836;
            this.m_Button3.Width = 151;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(147)))), ((int)(((byte)(147)))), ((int)(((byte)(147))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button2.DelayMouseInputPeriod = 0;
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontFamily = "微软雅黑";
            this.m_Button2.FontSizePixels = 15;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button2.Height = 69;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 597;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "BG";
            this.m_Button2.StyleName = "Glossy";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_Button2.TextHeight = 20;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 16;
            this.m_Button2.Top = 9;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = 525804456;
            this.m_Button2.Width = 22;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "BG";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_BG = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_BG) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_AlarmViewer);
            ((System.ComponentModel.ISupportInitialize)(this.m_AlarmViewer)).EndInit();
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_DigitalClock1);
            this.DrawingPrimitives.Add(this.m_DigitalClock2);
            this.DrawingPrimitives.Add(this.m_Button8);
            this.DrawingPrimitives.Add(this.m_Button7);
            this.DrawingPrimitives.Add(this.m_Button9);
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Picture5);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Button2);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
        }
        
        private void m_Button4_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "Click", "Show Screen", "SETTING", "");
            Neo.ApplicationFramework.Generated.Globals.SETTING.Show();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Reset Tag", "Tags.buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.buzzer.ResetTag();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Acknowledge All Alarms", "AlarmViewer", "");
            AlarmViewer.AcknowledgeAll();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Reset Tag", "Tags.flickerState", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.flickerState.ResetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Execute Script", "Flicker", "");
            Neo.ApplicationFramework.Generated.Globals.Flicker.ack();
        }
        
        private void m_Button8_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "Click", "Show Screen", "UNITS", "");
            Neo.ApplicationFramework.Generated.Globals.UNITS.Show();
        }
        
        private void m_Button7_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "Click", "Show Screen", "RUNSTOP", "");
            Neo.ApplicationFramework.Generated.Globals.RUNSTOP.Show();
        }
        
        private void m_Button9_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button9", "Click", "Show Screen", "HOME1", "");
            Neo.ApplicationFramework.Generated.Globals.HOME1.Show();
        }
        
        private void m_Button3_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "Click", "Show Screen", "CONFIG1_1", "");
            Neo.ApplicationFramework.Generated.Globals.CONFIG1_1.Show();
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "Click", "Show Screen", "REALALARM", "");
            Neo.ApplicationFramework.Generated.Globals.REALALARM.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(BG));
            this.m_Button1.Text = resources.GetText("BG.Button1.Text", "MUTE");
            this.m_Button.Text = resources.GetText("BG.Button.Text", "ACK");
            this.m_Button8.Text = resources.GetText("BG.Button8.Text", "INFORMATION");
            this.m_Button7.Text = resources.GetText("BG.Button7.Text", "RUN/STOP");
            this.m_Button9.Text = resources.GetText("BG.Button9.Text", "HOME");
            this.m_Button3.Text = resources.GetText("BG.Button3.Text", "USER SETTING");
            this.m_Button4.Text = resources.GetText("BG.Button4.Text", "SETTING");
            this.m_Button2.Text = resources.GetText("BG.Button2.Text", ">");
            resources.ApplyTexts(this.m_Button, "Texts", "BG.Button.Texts[0]", "确认", "BG.Button.Texts[1]", "ACK");
            resources.ApplyTexts(this.m_Button1, "Texts", "BG.Button1.Texts[0]", "消音", "BG.Button1.Texts[1]", "MUTE");
            resources.ApplyTexts(this.m_Button3, "Texts", "BG.Button3.Texts[0]", "用户设置", "BG.Button3.Texts[1]", "USER SETTING");
            resources.ApplyTexts(this.m_Button4, "Texts", "BG.Button4.Texts[0]", "综合设置", "BG.Button4.Texts[1]", "SETTING");
            resources.ApplyTexts(this.m_Button7, "Texts", "BG.Button7.Texts[0]", "运行/停止", "BG.Button7.Texts[1]", "RUN/STOP");
            resources.ApplyTexts(this.m_Button8, "Texts", "BG.Button8.Texts[0]", "模块详情", "BG.Button8.Texts[1]", "INFORMATION");
            resources.ApplyTexts(this.m_Button9, "Texts", "BG.Button9.Texts[0]", "主页", "BG.Button9.Texts[1]", "HOME");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_BG) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button4.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button1.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button8.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button7.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button9.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.LID"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button3.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
        }
    }
}
